/*
 * JSP generated by Resin 2.1.9 (built Tue Apr 15 14:28:40 PDT 2003)
 */

import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.io.*;
import java.util.*;
import com.jspsmart.upload.*;

public class _upload_0add__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html;charset=gb2312");
    request.setCharacterEncoding("GB2312");
    try {
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      com.jspsmart.upload.SmartUpload mySmartUpload;
      mySmartUpload = (com.jspsmart.upload.SmartUpload) pageContext.getAttribute("mySmartUpload");
      if (mySmartUpload == null) {
        mySmartUpload = new com.jspsmart.upload.SmartUpload();
        pageContext.setAttribute("mySmartUpload", mySmartUpload);
      }
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      
String uploadFileName1 = null;
String uploadFileName2 = null;
if(request.getMethod().equals("POST"))
{
 mySmartUpload.initialize(pageContext);
 mySmartUpload.upload();
  for (int i=0;i<mySmartUpload.getFiles().getCount();i++)
    {com.jspsmart.upload.File myFile = mySmartUpload.getFiles().getFile(i);
  
  		// Save it only if this file exists
      if (!myFile.isMissing())
	  
                  {String filedirectory=getServletContext().getRealPath("/")+"UploadFile\\";
                   if(myFile.getFieldName().equals("URL"))
				   { myFile.saveAs(filedirectory+myFile.getFileName(),mySmartUpload.SAVE_PHYSICAL);
                     uploadFileName1 = myFile.getFileName();                 
				    }
					
             }             
     }
	 out.print("<div align='center'><font color='#000000'>\u6587\u4ef6\u4e0a\u4f20\u6210\u529f\uff01</font></div>");

}
else 
{

      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      
}

    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 2057024151)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_upload_0add__jsp.java", "/bin/upload_Add.jsp");
    _caucho_line_map.add(3, 1);
    _caucho_line_map.add(1, 29);
    _caucho_line_map.add(3, 30);
    _caucho_line_map.add(14, 38);
    _caucho_line_map.add(51, 66);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("upload_Add.jsp"), 1116175856000L, 1644L);
    _caucho_depends.add(depend);
  }

  protected void _caucho_clearDepends()
  {
    _caucho_depends.clear();
  }

  private static byte []_jsp_string3;
  private static byte []_jsp_string2;
  private static byte []_jsp_string0;
  private static byte []_jsp_string1;
  static {
    try {
      _jsp_string3 = "\r\n<body leftmargin=\"0\" topmargin=\"0\">\r\n<form action=\"upload_Add.jsp\" method=\"post\" encType=multipart/form-data><table width=\"100%\"  border=\"0\" cellspacing=\"0\" cellpadding=\"1\">\r\n\r\n  <tr>\r\n    <td>\u3000\u3000<input name=\"URL\" type=\"file\" style=\"height:20;width:200 \">\r\n\u3000\u3000\r\n<input name=\"submit\" type=\"submit\" value=\"\u4e0a\u4f20\"></td>\r\n  </tr>\r\n</table>\r\n</form></body>\r\n".getBytes("GB2312");
      _jsp_string2 = "\r\n<html>\r\n<head>\r\n<title>\u97f3\u4e50\u9891\u9053\u7ba1\u7406\u7cfb\u7edf V1.0</title>\r\n<meta name=\"GENERATOR\" content=\"Microsoft FrontPage 3.0\">\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"Style2.css\">\r\n\r\n</head>\r\n\r\n\r\n".getBytes("GB2312");
      _jsp_string0 = "\r\n\r\n".getBytes("GB2312");
      _jsp_string1 = "\r\n".getBytes("GB2312");
    } catch (java.io.UnsupportedEncodingException e) {
      e.printStackTrace();
    }
  }
}
