/*
 * JSP generated by Resin 2.1.9 (built Tue Apr 15 14:28:40 PDT 2003)
 */

import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.io.*;
import java.util.*;
import java.net.*;
import chat.*;

public class _userlist__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html;charset=gb2312");
    request.setCharacterEncoding("GB2312");
    try {
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
  ChatLogin chatLogin = new ChatLogin();

      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      //if (request.getParameter("UserName")==null)  response.sendRedirect("login.jsp");
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
String[] arr= chatLogin.userList((String)request.getServerName());
if (arr.length==1) out.print("<tr onmouseout=this.style.backgroundColor='' onmouseover=this.style.backgroundColor='#BFDFFF' style='cursor:hand;' class='tr'><td class='td'><font color=#ffffff>"+arr[0]+"</font></td></tr>");
else
for (int i=1;i<arr.length;i++) out.print("<tr onmouseout=this.style.backgroundColor='' onmouseover=this.style.backgroundColor='#1A7BCD' style='cursor:hand;' class='tr'><td class='td'><font color=#ffffff>"+arr[i]+"</font></td></tr>");
         
 //int port=10000;
// Socket s=null;
//DataInputStream io_in=null;
 //DataOutputStream io_out=null;
//s=new Socket(request.getServerName(),port);
  //io_in=new DataInputStream(s.getInputStream());
 // io_out=new DataOutputStream(s.getOutputStream());
//io_out.writeUTF("www");
//while(true){
//out.print(io_in.readUTF());
///} 

      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 2057024151)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_userlist__jsp.java", "/bin/userList.jsp");
    _caucho_line_map.add(5, 1);
    _caucho_line_map.add(1, 30);
    _caucho_line_map.add(43, 39);
    _caucho_line_map.add(44, 41);
    _caucho_line_map.add(48, 46);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("userList.jsp"), 1127496844000L, 2042L);
    _caucho_depends.add(depend);
  }

  protected void _caucho_clearDepends()
  {
    _caucho_depends.clear();
  }

  private static byte []_jsp_string1;
  private static byte []_jsp_string2;
  private static byte []_jsp_string0;
  static {
    try {
      _jsp_string1 = "\r\n<meta http-equiv=\"refresh\" content=\"10;url='userList.jsp'\">\r\n<style type=\"text/css\">\r\nBody\r\n{\r\n	FONT-FAMILY: \"Verdana, Arial, \u5b8b\u4f53\";\r\n	FONT-SIZE: 9pt;\r\n	text-decoration: none;\r\n	line-height: 150%;\r\n	background-color: #3399FF;\r\n	color: #FFFFFF;\r\n	FONT-SIZE: 9pt;\r\n   SCROLLBAR-FACE-COLOR: #E8EFF9;\r\n	SCROLLBAR-HIGHLIGHT-COLOR: #E8EFF9;\r\n	SCROLLBAR-SHADOW-COLOR: #E8EFF9;\r\n	SCROLLBAR-3DLIGHT-COLOR: #E8EFF9;\r\n	SCROLLBAR-ARROW-COLOR: #A5BFEC;\r\n	SCROLLBAR-TRACK-COLOR: #A5BFEC;\r\n	SCROLLBAR-DARKSHADOW-COLOR: #E8EFF9;\r\n}\r\nTd\r\n{\r\n	FONT-FAMILY: \"Verdana, Arial, \u5b8b\u4f53\";\r\n	FONT-SIZE: 9pt;\r\n	color: #FFFFFF;\r\n}\r\nTr\r\n{\r\n	FONT-FAMILY: \"Verdana, Arial, \u5b8b\u4f53\";\r\n	FONT-SIZE: 9pt;\r\n	color: #cccccc;\r\n}\r\n</style>\r\n<body leftmargin=\"0\" topmargin=\"0\" bgcolor=\"#0066FF\">\r\n<table width=\"100%\"  border=\"0\" cellspacing=\"1\" cellpadding=\"1\">\r\n  ".getBytes("GB2312");
      _jsp_string2 = "\r\n</table>\r\n</body>\r\n".getBytes("GB2312");
      _jsp_string0 = "\r\n".getBytes("GB2312");
    } catch (java.io.UnsupportedEncodingException e) {
      e.printStackTrace();
    }
  }
}
